### ISSUE TITLE
背景模式切换

### ISSUE THREAD

**Issue by PiPi0413** [mjjh1717/ai-beehive-web#33]
想要将模式默认切换为夜晚,应该修改哪部分代码

**Comment by mjjh1717** [comment]
坐下角图标切换,代码再vuetheme状态中
![image](https://github.com/mjjh1717/ai-beehive-web/assets/56958167/004c5884-8503-4ffb-9524-4d47495b3f60)

**Comment by PiPi0413** [comment]
Please give us a little more detailed hint!

**Comment by mjjh1717** [comment]
已经支持直接在此处切换 
![image](https://github.com/mjjh1717/ai-beehive-web/assets/56958167/dbd54e11-68e9-41d8-9750-e9029d5b6a75)
